### PR TITLE
Some website updates

### PR DESCRIPTION
**Pull request by maul-esel**
- Developers are now shown on a separate page
  - on main page:
image
  - developers page: 
image
- Awards are now shown on a separate page
  - on main page: 
image
  - awards page: 
image
- Tool languages are now shown as badges: 
image

### CODE REVIEW

**Comment by schuessf** [comment]
I will take a closer look soon and deploy it on my own, but I definitely appreciate those changes in general.

> Developers are now shown on a separate page

Both pages have the very same formulation ("Most ULTIMATE developers..."). Should we maybe change this sentence on the main page to sth. shorter like "All developers/contributors/... can be found here"?

> Awards are now shown on a separate page
> on main page:

This does not really stand out to me. Could we maybe add a trophy, the most recent awards or sth. similar?

> awards page:

Look great!

> Tool languages are now shown as badges:

Looks great! Could we change maybe the representation for `Automata_script` to sth. without a underscore? Could this even be done directly in the config?

Maybe another small request: Would it be possible to preselect a language, when you open the webinterface (definitely for tools that only support one language, maybe also the others)? I think this would improve the usability by a lot!

**Comment by danieldietsch** [comment]
Links on developers
* Could you link to Nico and Elisabeth on SWT?
* Julian Jarecki is listed twice and could be linked to https://www.julian-jarecki.com
* Unlink German Fordinal, the page seems inactive
* Link Jan Leike: https://jan.leike.name

**Comment by danieldietsch** [comment]
Perhaps you could also consider using .svgs instead of .pngs for the awards. And not trophies but medals, e.g. 
or something from https://www.svgrepo.com/svg/7725/gold-medal

**Comment by danieldietsch** [comment]
But great job! In particular the awards page :)

**Review by danieldietsch — APPROVED** [review]

**Comment by maul-esel** [comment]
> Perhaps you could also consider using .svgs instead of .pngs for the awards. And not trophies but medals, e.g.  or something from https://www.svgrepo.com/svg/7725/gold-medal

I searched a bit, but couldn't find nice SVG medals. I wasn't aware of this website, looks useful. What do you think?

image

**Comment by danieldietsch** [comment]
Much better! But sort the Taipain medals so that silver comes first.

My last notes on awards is btw this:
Summary
SV-COMP Automizer 19x3th, 16x2th, 11x1th


SV-COMP 2022
Automizer won the category termination 
Automizer was second in NoOverflows
GemCutter was third in ConcurrencySafety
Taipan was third in NoOverflows
Automizer was third in the overall ranking 


SV-COMP 2021 
Automizer was third in MemSafety
Automizer was third in ConcurrencySafety
Automizer was second in NoOverflows
Taipan was third in NoOverflows
Automizer won the category termination 
Automizer was third in the overall ranking 
Automizer was third in the falsification ranking 


SV-COMP 2020
Automizer was second in the overall ranking.
Automizer won the category Termination.
Automizer was second in the category NoOverflows.
Taipan was third in the category NoOverflows.


SV-COMP 2019
Automizer was third in the overall ranking.
Automizer won the category NoOverflows 
Automizer won the category Termination.
Taipan was second in the category NoOverflows.


SV-COMP 2018
Automizer won the category NoOverflows 
Automizer won the category Termination
Automizer was second in the overall ranking.
Automizer was second in the category SoftwareSystems.
Automizer was third in the category ReachSafety.
Kojak was third in the category MemSafety.
Taipan was third in the category NoOverflows.


SV-COMP 2017
Automizer won the overall ranking.
Automizer won the category Termination.
Automizer was second in the category MemSafety 
Automizer was second in the category Overflows.
Taipan was second in the category SoftwareSystems.
Automizer was third in the categories ReachSafety 
Automizer was third in the categories SoftwareSystems.
Taipan was third in the category Overflows.


SV-COMP 2016
Automizer won the overall ranking
Automizer won the overall falsification ranking.
Automizer was second in the category Termination.


SV-COMP 2015
Automizer was second in the overall ranking 
Automizer was second in the category Recursive
Automizer was second in the category Termination
Kojak was second in the category Arrays.
Automizer was third in the category Arrays 
Automizer was third in the category Sequentialized.


SV-COMP 2014
Automizer was second in the category Recursive.
Kojak was third in the category Recursive.


Termination Competition 2019
Automizer won the category "C Programs" onf the track Termination of Programms. 


RERS Challenge 2018
Automizer won the Sequential Reachability Track.
Automizer won gold in the category Reachability plain 
Automizer won gold in the category Reachability arithmetic.
Automizer won silver in the category Reachability data structures.


RERS Challenge 2016
Automizer won the Reachability overall ranking. 
Automizer won gold in the category Reachability plain 
Automizer won gold in the category Reachability arithmetic.
Automizer won silver in the category Reachability data structures.


Termination Competition 2015
Automizer won the category Termination of Programming Languages.


Termination Competition 2014
Automizer was second in the category Termination of Programming Languages.

**Comment by maul-esel** [comment]
@danieldietsch Wo packen wir Credits für die SVG-Grafiken hin? Gibt es da schon eine Stelle?

@schuessf I agree the landing page could still be made nicer. Maybe let's discuss and sketch/try out some variants live at a meeting next week or so? It doesn't all have to go in this PR :)

**Comment by danieldietsch** [comment]
Waren die nicht CC0?

**Comment by maul-esel** [comment]
Die gerade genutzten haben MIT
> Medal icons by <a href="https://github.com/twitter/twemoji?ref=svgrepo.com" target="_blank">Twitter</a> in MIT License via <a href="https://www.svgrepo.com/" target="_blank">SVG Repo</a>

**Comment by danieldietsch** [comment]
Perhaps we should add an "impressum", similar to SWT: https://swt.informatik.uni-freiburg.de/impressum
And then add these licenses under Further Information.

**Comment by danieldietsch** [comment]
So, basically something that links to this university page and has a image license section .

**Comment by bahnwaerter** [comment]
> @bahnwaerter github won't let me add you as reviewer, but please feel invited :)

Your changes for the website look good to me. I really like the new layout for the awards. The new visualization makes all awards easier and quicker to read. In addition, the main page is no longer overloaded. That's great!

In order not to get any legal problems, an imprint should be added or a reference to an imprint of the university should be made, as @danieldietsch has already proposed.

**Comment by maul-esel** [comment]
@danieldietsch The impressum you linked to looks interesting :D 
image

I'll add a page.

**Comment by danieldietsch** [comment]
I know :p -- if its good enough for SWT, its good enough for us.

**Comment by maul-esel** [comment]
The imprint page:
image
image

I've also added some better images for the past few SV-COMPs: 
image

**Comment by danieldietsch** [comment]
Imprint: 👍 
Do the images replace the medals or augment them? It would probably be good to still have it as text, in particular for web searches.

**Comment by maul-esel** [comment]
The images replace the "text images" saying simply "SV-COMP 20xx" because we had no photo (if you look at the screenshots at the top, you can see the "TERM-COMP 2015" image).

Once you click on "Show details", you will see the medals, same as before.

I think web search will nevertheless struggle with this page due to all the dynamic loading of content. IIRC "only" google executes js, and even there I'm not sure if these awards will found... I talked with @Heizmann yesterday about replacing this dynamic loading with a static site generator (I suggest jekyll), and he seemed open to it. What do you think, @danieldietsch ? (not for this PR, but medium-term I might be willing into doing this.)

**Comment by danieldietsch** [comment]
I am all for it (if it has a README that explains how one uses it, or a Jenkins job, etc.)

I think it should not require any changes, right? Everything should be separated from the web interface.

**Review by schuessf — APPROVED** [review]

**Comment by maul-esel** [comment]
> I think it should not require any changes, right? Everything should be separated from the web interface.

You mean no changes to the backend? Then yes, that should be separate.

**Pull request merged**
